# Generated by Django 5.1.5 on 2025-03-02 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediamodels', '0004_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
