# Generated by Django 5.1.5 on 2025-03-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediamodels', '0008_alter_product_filters'),
        ('organiqueFood', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['created']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='filters',
        ),
        migrations.AddField(
            model_name='product',
            name='filters',
            field=models.ManyToManyField(blank=True, null=True, related_name='filter', to='organiqueFood.productsfilter'),
        ),
    ]
