# Generated by Django 5.1.5 on 2025-03-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediamodels', '0009_alter_product_options_remove_product_filters_and_more'),
        ('organiqueFood', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='filters',
            field=models.ManyToManyField(blank=True, related_name='filter', to='organiqueFood.productsfilter'),
        ),
    ]
